server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/returnsystem
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

return.policy.window-days=30

jwt.secret=ce1896a29d9a5af0d0105c76c954856e4fee8c76b008ba5139bf4c9a35485c18
jwt.access-token-expiry-ms=900000
jwt.refresh-token-expiry-ms=604800000
